# Generated by Django 4.2.4 on 2023-08-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop_main', '0003_basket_basketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
