# Generated by Django 4.2.4 on 2023-08-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop_main', '0004_userprofile_email_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
