# Generated by Django 4.2.4 on 2023-08-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop_main', '0005_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
